install:
    - nuget restore
    - nuget install buildBom -Pre

build:
  project: integration-bdio.NET.sln
  verbosity: detailed

environment:
  my_variable:
    secure: v6/PPE4nIxNrzJRi7gxB2q6bBGRBwPjUZ4hF/LUv+Hc=
    
after_test: 
# generate report for NUnit testing framework:
    - cmd: BuildBom.0.0.4-alpha\tools\buildBom.exe --solution_path=C:\projects\integration-bdio-net\integration-bdio.NET.sln --hub_deploy_bdio=false
    - cmd: packages\OpenCover.4.6.166\tools\OpenCover.Console.exe -register:user -filter:"+[*]*" -target:"packages\NUnit.ConsoleRunner.3.6.0\tools\nunit3-console.exe" -targetargs:"/domain:single integration-bdio.NET-test\bin\Debug\integration-bdio.NET-test.dll" -output:coverage.xml
    - cmd: packages\coveralls.io.1.3.4\tools\coveralls.net.exe --opencover coverage.xml
    

deploy:
  provider: NuGet
  server:                  # remove to push to NuGet.org
  api_key:
    secure: OMdcth+rc6XzW6CPCrnzK0t5YGf/124tQdRpU8vqbAXIuYQJdwuwdst/Q8DtQH3
  skip_symbols: false
  symbol_server:           # remove to push symbols to SymbolSource.org
  artifact: /.*\.nupkg/
