install:
    - nuget restore
    - nuget install Hub-NuGet -Pre

build:
  project: integration-bdio.NET.sln
  verbosity: detailed

environment:
  my_variable:
    secure: v6/PPE4nIxNrzJRi7gxB2q6bBGRBwPjUZ4hF/LUv+Hc=
    
after_test: 
# generate report for NUnit testing framework:
  
    - cmd: packages\OpenCover.4.6.166\tools\OpenCover.Console.exe -register:user -filter:"+[*]*" -target:"packages\NUnit.ConsoleRunner.3.6.0\tools\nunit3-console.exe" -targetargs:"/domain:single integration-bdio.NET-test\bin\Debug\integration-bdio.NET-test.dll" -output:coverage.xml
    - cmd: packages\coveralls.io.1.3.4\tools\coveralls.net.exe --opencover coverage.xml

on_success:
- cmd: Hub-NuGet.1.0.0-beta\tools\buildBom.exe --hub_deploy_bdio=false --excluded_modules=integration-bdio.NET-test -v
- curl -s https://test.duckbuild.io/batch/appveyor > appveyor.bat
- appveyor blackduck\*_bdio.jsonld
- del appveyor.bat    
