//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.blackducksoftware.integration.hub.bdio.simple.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("com.blackducksoftware.integration.hub.bdio.simple.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///{
        ///  &quot;specVersion&quot;: &quot;1.1.0&quot;,
        ///  &quot;@id&quot;: &quot;uuid:45772d33-5353-44f1-8681-3d8a15540646&quot;,
        ///  &quot;@type&quot;: &quot;BillOfMaterials&quot;,
        ///  &quot;name&quot;: &quot;gradleTestProject Black Duck I/O Export&quot;
        ///},
        ///{
        ///  &quot;revision&quot;: &quot;99.5-SNAPSHOT&quot;,
        ///  &quot;@id&quot;: &quot;data:com.blackducksoftware.gradle.test/gradleTestProject/99.5-SNAPSHOT&quot;,
        ///  &quot;@type&quot;: &quot;Project&quot;,
        ///  &quot;name&quot;: &quot;gradleTestProject&quot;,
        ///  &quot;externalIdentifier&quot;: {
        ///    &quot;externalSystemTypeId&quot;: &quot;maven&quot;,
        ///    &quot;externalId&quot;: &quot;com.blackducksoftware.gradle.test:gradleTestProject:99.5-SNAPSHOT&quot;
        ///  },
        ///  &quot;r [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string sample {
            get {
                return ResourceManager.GetString("sample", resourceCulture);
            }
        }
    }
}
